spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pagila
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-auth-server.com/auth/realms/your-realm
          jwk-set-uri: https://your-auth-server.com/auth/realms/your-realm/protocol/openid-connect/certs
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - profile
              - email
          pagila-auth:
            client-id: ${PAGILA_CLIENT_ID:pagila-api}
            client-secret: ${PAGILA_CLIENT_SECRET:your-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read
              - write
        provider:
          pagila-auth:
            authorization-uri: https://your-auth/-server.com/oauth2/authorize
            token-uri: https://your-auth-server.com/oauth2/token
            user-info-uri: https://your-auth-server.com/oauth2/userinfo
            jwk-set-uri: https://your-auth-server.com/.well-known/jwks.json
jwt:
  secret: your-secure-secret-key
  expiration: 86400000
